Initial Debugging - finds problem at return parser.parse_args()

> /Users/Gantt/Documents/UW Python/UW Python 220/SP_Python220B_2019/students/christopher_gantt/lesson02/assignment/code/charges_calc.py(3)<module>()
-> '''
(Pdb) n
> /Users/Gantt/Documents/UW Python/UW Python 220/SP_Python220B_2019/students/christopher_gantt/lesson02/assignment/code/charges_calc.py(4)<module>()
-> import argparse
(Pdb) n
> /Users/Gantt/Documents/UW Python/UW Python 220/SP_Python220B_2019/students/christopher_gantt/lesson02/assignment/code/charges_calc.py(5)<module>()
-> import json
(Pdb) n
> /Users/Gantt/Documents/UW Python/UW Python 220/SP_Python220B_2019/students/christopher_gantt/lesson02/assignment/code/charges_calc.py(6)<module>()
-> import datetime
(Pdb) n
> /Users/Gantt/Documents/UW Python/UW Python 220/SP_Python220B_2019/students/christopher_gantt/lesson02/assignment/code/charges_calc.py(7)<module>()
-> import math
(Pdb) n
> /Users/Gantt/Documents/UW Python/UW Python 220/SP_Python220B_2019/students/christopher_gantt/lesson02/assignment/code/charges_calc.py(9)<module>()
-> def parse_cmd_arguments():
(Pdb) n
> /Users/Gantt/Documents/UW Python/UW Python 220/SP_Python220B_2019/students/christopher_gantt/lesson02/assignment/code/charges_calc.py(18)<module>()
-> def load_rentals_file(filename):
(Pdb) n
> /Users/Gantt/Documents/UW Python/UW Python 220/SP_Python220B_2019/students/christopher_gantt/lesson02/assignment/code/charges_calc.py(27)<module>()
-> def calculate_additional_fields(data):
(Pdb) n
> /Users/Gantt/Documents/UW Python/UW Python 220/SP_Python220B_2019/students/christopher_gantt/lesson02/assignment/code/charges_calc.py(42)<module>()
-> def save_to_json(filename, data):
(Pdb) n
> /Users/Gantt/Documents/UW Python/UW Python 220/SP_Python220B_2019/students/christopher_gantt/lesson02/assignment/code/charges_calc.py(47)<module>()
-> if __name__ == "__main__":
(Pdb) n
> /Users/Gantt/Documents/UW Python/UW Python 220/SP_Python220B_2019/students/christopher_gantt/lesson02/assignment/code/charges_calc.py(48)<module>()
-> ARGS = parse_cmd_arguments()
(Pdb) s
--Call--
> /Users/Gantt/Documents/UW Python/UW Python 220/SP_Python220B_2019/students/christopher_gantt/lesson02/assignment/code/charges_calc.py(9)parse_cmd_arguments()
-> def parse_cmd_arguments():
(Pdb) s
> /Users/Gantt/Documents/UW Python/UW Python 220/SP_Python220B_2019/students/christopher_gantt/lesson02/assignment/code/charges_calc.py(11)parse_cmd_arguments()
-> parser = argparse.ArgumentParser(description='Process some integers.')
(Pdb) n
> /Users/Gantt/Documents/UW Python/UW Python 220/SP_Python220B_2019/students/christopher_gantt/lesson02/assignment/code/charges_calc.py(12)parse_cmd_arguments()
-> parser.add_argument('-i', '--input', help='input JSON file', required=True)
(Pdb) n
> /Users/Gantt/Documents/UW Python/UW Python 220/SP_Python220B_2019/students/christopher_gantt/lesson02/assignment/code/charges_calc.py(13)parse_cmd_arguments()
-> parser.add_argument('-o', '--output', help='ouput JSON file', required=True)
(Pdb) n
> /Users/Gantt/Documents/UW Python/UW Python 220/SP_Python220B_2019/students/christopher_gantt/lesson02/assignment/code/charges_calc.py(15)parse_cmd_arguments()
-> return parser.parse_args()
(Pdb) n
usage: charges_calc.py [-h] -i INPUT -o OUTPUT
charges_calc.py: error: the following arguments are required: -i/--input, -o/--output
SystemExit: 2







2nd Debugger, shows first problem was solved by adding the input and output as arguments in the command line.
python charges_calc.py -i source.json -o out.json

Chriss-MacBook-Pro:code Gantt$ python -m pdb charges_calc.py -i source.json -o out.json
> /Users/Gantt/Documents/UW Python/UW Python 220/SP_Python220B_2019/students/christopher_gantt/lesson02/assignment/code/charges_calc.py(3)<module>()
-> '''
(Pdb) 
(Pdb) n
> /Users/Gantt/Documents/UW Python/UW Python 220/SP_Python220B_2019/students/christopher_gantt/lesson02/assignment/code/charges_calc.py(4)<module>()
-> import argparse
(Pdb) n
> /Users/Gantt/Documents/UW Python/UW Python 220/SP_Python220B_2019/students/christopher_gantt/lesson02/assignment/code/charges_calc.py(5)<module>()
-> import json
(Pdb) n
> /Users/Gantt/Documents/UW Python/UW Python 220/SP_Python220B_2019/students/christopher_gantt/lesson02/assignment/code/charges_calc.py(6)<module>()
-> import datetime
(Pdb) n
> /Users/Gantt/Documents/UW Python/UW Python 220/SP_Python220B_2019/students/christopher_gantt/lesson02/assignment/code/charges_calc.py(7)<module>()
-> import math
(Pdb) n
> /Users/Gantt/Documents/UW Python/UW Python 220/SP_Python220B_2019/students/christopher_gantt/lesson02/assignment/code/charges_calc.py(9)<module>()
-> def parse_cmd_arguments():
(Pdb) n
> /Users/Gantt/Documents/UW Python/UW Python 220/SP_Python220B_2019/students/christopher_gantt/lesson02/assignment/code/charges_calc.py(18)<module>()
-> def load_rentals_file(filename):
(Pdb) n
> /Users/Gantt/Documents/UW Python/UW Python 220/SP_Python220B_2019/students/christopher_gantt/lesson02/assignment/code/charges_calc.py(27)<module>()
-> def calculate_additional_fields(data):
(Pdb) n
> /Users/Gantt/Documents/UW Python/UW Python 220/SP_Python220B_2019/students/christopher_gantt/lesson02/assignment/code/charges_calc.py(42)<module>()
-> def save_to_json(filename, data):
(Pdb) n
> /Users/Gantt/Documents/UW Python/UW Python 220/SP_Python220B_2019/students/christopher_gantt/lesson02/assignment/code/charges_calc.py(47)<module>()
-> if __name__ == "__main__":
(Pdb) n
> /Users/Gantt/Documents/UW Python/UW Python 220/SP_Python220B_2019/students/christopher_gantt/lesson02/assignment/code/charges_calc.py(48)<module>()
-> ARGS = parse_cmd_arguments()
(Pdb) s
--Call--
> /Users/Gantt/Documents/UW Python/UW Python 220/SP_Python220B_2019/students/christopher_gantt/lesson02/assignment/code/charges_calc.py(9)parse_cmd_arguments()
-> def parse_cmd_arguments():
(Pdb) s
> /Users/Gantt/Documents/UW Python/UW Python 220/SP_Python220B_2019/students/christopher_gantt/lesson02/assignment/code/charges_calc.py(11)parse_cmd_arguments()
-> parser = argparse.ArgumentParser(description='Process some integers.')
(Pdb) n
> /Users/Gantt/Documents/UW Python/UW Python 220/SP_Python220B_2019/students/christopher_gantt/lesson02/assignment/code/charges_calc.py(12)parse_cmd_arguments()
-> parser.add_argument('-i', '--input', help='input JSON file', required=True)
(Pdb) n
> /Users/Gantt/Documents/UW Python/UW Python 220/SP_Python220B_2019/students/christopher_gantt/lesson02/assignment/code/charges_calc.py(13)parse_cmd_arguments()
-> parser.add_argument('-o', '--output', help='ouput JSON file', required=True)
(Pdb) n
> /Users/Gantt/Documents/UW Python/UW Python 220/SP_Python220B_2019/students/christopher_gantt/lesson02/assignment/code/charges_calc.py(15)parse_cmd_arguments()
-> return parser.parse_args()
(Pdb) n
--Return--
> /Users/Gantt/Documents/UW Python/UW Python 220/SP_Python220B_2019/students/christopher_gantt/lesson02/assignment/code/charges_calc.py(15)parse_cmd_arguments()->Namespace(inp...ut='out.json')
-> return parser.parse_args()
(Pdb) n
> /Users/Gantt/Documents/UW Python/UW Python 220/SP_Python220B_2019/students/christopher_gantt/lesson02/assignment/code/charges_calc.py(49)<module>()
-> DATA = load_rentals_file(ARGS.input)
(Pdb)

--------------------

Debugger 3, find except for def load_rental_files
File Not Found Error

Chriss-MacBook-Pro:code Gantt$ python -m pdb charges_calc.py -i source.json -o out.json
> /Users/Gantt/Documents/UW Python/UW Python 220/SP_Python220B_2019/students/christopher_gantt/lesson02/assignment/code/charges_calc.py(3)<module>()
-> '''
(Pdb) n
> /Users/Gantt/Documents/UW Python/UW Python 220/SP_Python220B_2019/students/christopher_gantt/lesson02/assignment/code/charges_calc.py(4)<module>()
-> import argparse
(Pdb) n
> /Users/Gantt/Documents/UW Python/UW Python 220/SP_Python220B_2019/students/christopher_gantt/lesson02/assignment/code/charges_calc.py(5)<module>()
-> import json
(Pdb) n
n
n> /Users/Gantt/Documents/UW Python/UW Python 220/SP_Python220B_2019/students/christopher_gantt/lesson02/assignment/code/charges_calc.py(6)<module>()
-> import datetime
(Pdb) n
n
> /Users/Gantt/Documents/UW Python/UW Python 220/SP_Python220B_2019/students/christopher_gantt/lesson02/assignment/code/charges_calc.py(7)<module>()
-> import math
(Pdb) n
> /Users/Gantt/Documents/UW Python/UW Python 220/SP_Python220B_2019/students/christopher_gantt/lesson02/assignment/code/charges_calc.py(8)<module>()
-> import logging
(Pdb) n
> /Users/Gantt/Documents/UW Python/UW Python 220/SP_Python220B_2019/students/christopher_gantt/lesson02/assignment/code/charges_calc.py(10)<module>()
-> log_format = '%(asctime)s %(filename)s:%(lineno)-3d %(levelname)s %(message)s'
(Pdb) n
> /Users/Gantt/Documents/UW Python/UW Python 220/SP_Python220B_2019/students/christopher_gantt/lesson02/assignment/code/charges_calc.py(11)<module>()
-> log_file = datetime.datetime.now().strftime('%Y-%m-%d')+'.log'
(Pdb) n
> /Users/Gantt/Documents/UW Python/UW Python 220/SP_Python220B_2019/students/christopher_gantt/lesson02/assignment/code/charges_calc.py(12)<module>()
-> logging.basicConfig(level=logging.DEBUG, format=log_format, filename=log_file)
(Pdb) n
> /Users/Gantt/Documents/UW Python/UW Python 220/SP_Python220B_2019/students/christopher_gantt/lesson02/assignment/code/charges_calc.py(29)<module>()
-> def parse_cmd_arguments():
(Pdb) n
> /Users/Gantt/Documents/UW Python/UW Python 220/SP_Python220B_2019/students/christopher_gantt/lesson02/assignment/code/charges_calc.py(43)<module>()
-> def load_rentals_file(filename):
(Pdb) n
> /Users/Gantt/Documents/UW Python/UW Python 220/SP_Python220B_2019/students/christopher_gantt/lesson02/assignment/code/charges_calc.py(53)<module>()
-> def calculate_additional_fields(data):
(Pdb) n
> /Users/Gantt/Documents/UW Python/UW Python 220/SP_Python220B_2019/students/christopher_gantt/lesson02/assignment/code/charges_calc.py(68)<module>()
-> def save_to_json(filename, data):
(Pdb) n
> /Users/Gantt/Documents/UW Python/UW Python 220/SP_Python220B_2019/students/christopher_gantt/lesson02/assignment/code/charges_calc.py(73)<module>()
-> if __name__ == "__main__":
(Pdb) n
> /Users/Gantt/Documents/UW Python/UW Python 220/SP_Python220B_2019/students/christopher_gantt/lesson02/assignment/code/charges_calc.py(74)<module>()
-> ARGS = parse_cmd_arguments()
(Pdb) n
> /Users/Gantt/Documents/UW Python/UW Python 220/SP_Python220B_2019/students/christopher_gantt/lesson02/assignment/code/charges_calc.py(75)<module>()
-> DATA = load_rentals_file(ARGS.input)
(Pdb) s
--Call--
> /Users/Gantt/Documents/UW Python/UW Python 220/SP_Python220B_2019/students/christopher_gantt/lesson02/assignment/code/charges_calc.py(43)load_rentals_file()
-> def load_rentals_file(filename):
(Pdb) n
> /Users/Gantt/Documents/UW Python/UW Python 220/SP_Python220B_2019/students/christopher_gantt/lesson02/assignment/code/charges_calc.py(45)load_rentals_file()
-> with open(filename) as file:
(Pdb) n
FileNotFoundError: [Errno 2] No such file or directory: 'source.json'
> /Users/Gantt/Documents/UW Python/UW Python 220/SP_Python220B_2019/students/christopher_gantt/lesson02/assignment/code/charges_calc.py(45)load_rentals_file()




Debugger 4, error on DATA = calculate_additional_fields(DATA) in name=main block
Gonna try to change the variable names so DATA doesn't overwrite itself.

That was unsuccessful. Gonna dig deeper.

Error is happening within the calculate_additional_field function. Explore...

> /Users/Gantt/Documents/UW Python/UW Python 220/SP_Python220B_2019/students/christopher_gantt/lesson02/assignment/code/charges_calc.py(69)<module>()
-> if __name__ == "__main__":
(Pdb) n
> /Users/Gantt/Documents/UW Python/UW Python 220/SP_Python220B_2019/students/christopher_gantt/lesson02/assignment/code/charges_calc.py(70)<module>()
-> ARGS = parse_cmd_arguments()
(Pdb) n
> /Users/Gantt/Documents/UW Python/UW Python 220/SP_Python220B_2019/students/christopher_gantt/lesson02/assignment/code/charges_calc.py(71)<module>()
-> DATA = load_rentals_file(ARGS.input)
(Pdb) n
> /Users/Gantt/Documents/UW Python/UW Python 220/SP_Python220B_2019/students/christopher_gantt/lesson02/assignment/code/charges_calc.py(72)<module>()
-> DATA = calculate_additional_fields(DATA)
(Pdb) n
SystemExit: 0
> /Users/Gantt/Documents/UW Python/UW Python 220/SP_Python220B_2019/students/christopher_gantt/lesson02/assignment/code/charges_calc.py(72)<module>()
-> DATA = calculate_additional_fields(DATA)
(Pdb) Traceback (most recent call last):
  File "/anaconda3/lib/python3.7/pdb.py", line 1697, in main
    pdb._runscript(mainpyfile)
  File "/anaconda3/lib/python3.7/pdb.py", line 1566, in _runscript
    self.run(statement)
  File "/anaconda3/lib/python3.7/bdb.py", line 585, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/Users/Gantt/Documents/UW Python/UW Python 220/SP_Python220B_2019/students/christopher_gantt/lesson02/assignment/code/charges_calc.py", line 72, in <module>
    DATA = calculate_additional_fields(DATA)
  File "/anaconda3/lib/python3.7/bdb.py", line 94, in trace_dispatch
    return self.dispatch_exception(frame, arg)
  File "/anaconda3/lib/python3.7/bdb.py", line 173, in dispatch_exception
    self.user_exception(frame, arg)
  File "/anaconda3/lib/python3.7/pdb.py", line 312, in user_exception
    self.interaction(frame, exc_traceback)
  File "/anaconda3/lib/python3.7/pdb.py", line 352, in interaction
    self._cmdloop()
  File "/anaconda3/lib/python3.7/pdb.py", line 321, in _cmdloop
    self.cmdloop()
  File "/anaconda3/lib/python3.7/cmd.py", line 126, in cmdloop
    line = input(self.prompt)
ValueError: I/O operation on closed file.
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> /anaconda3/lib/python3.7/cmd.py(126)cmdloop()
-> line = input(self.prompt)
(Pdb) Traceback (most recent call last):
  File "/anaconda3/lib/python3.7/pdb.py", line 1697, in main
    pdb._runscript(mainpyfile)
  File "/anaconda3/lib/python3.7/pdb.py", line 1566, in _runscript
    self.run(statement)
  File "/anaconda3/lib/python3.7/bdb.py", line 585, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/Users/Gantt/Documents/UW Python/UW Python 220/SP_Python220B_2019/students/christopher_gantt/lesson02/assignment/code/charges_calc.py", line 72, in <module>
    DATA = calculate_additional_fields(DATA)
  File "/anaconda3/lib/python3.7/bdb.py", line 94, in trace_dispatch
    return self.dispatch_exception(frame, arg)
  File "/anaconda3/lib/python3.7/bdb.py", line 173, in dispatch_exception
    self.user_exception(frame, arg)
  File "/anaconda3/lib/python3.7/pdb.py", line 312, in user_exception
    self.interaction(frame, exc_traceback)
  File "/anaconda3/lib/python3.7/pdb.py", line 352, in interaction
    self._cmdloop()
  File "/anaconda3/lib/python3.7/pdb.py", line 321, in _cmdloop
    self.cmdloop()
  File "/anaconda3/lib/python3.7/cmd.py", line 126, in cmdloop
    line = input(self.prompt)
ValueError: I/O operation on closed file.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/anaconda3/lib/python3.7/pdb.py", line 1724, in <module>
    pdb.main()
  File "/anaconda3/lib/python3.7/pdb.py", line 1716, in main
    pdb.interaction(None, t)
  File "/anaconda3/lib/python3.7/pdb.py", line 352, in interaction
    self._cmdloop()
  File "/anaconda3/lib/python3.7/pdb.py", line 321, in _cmdloop
    self.cmdloop()
  File "/anaconda3/lib/python3.7/cmd.py", line 126, in cmdloop
    line = input(self.prompt)
ValueError: I/O operation on closed file.

